###PANDAS

In [2]:
%pip install pandas

Collecting pandas
  Downloading pandas-2.2.3-cp312-cp312-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\tejas\venv\lib\site-packages (from pandas) (2.2.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\tejas\venv\lib\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\tejas\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-2.2.3-cp312-cp312-win_amd64.whl (11.5 MB)
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   ------------- -------------------------- 3.9/11.5 MB 18.1 MB/s eta 0:00:01
   ------------------------- -------------- 7.3/11.5 MB 17.4 MB/s eta 0:00:01
   ---------------------------------------  11.3/11.5 MB 17.6 MB/s eta 0:00:01
   ---------------------------------------- 11.5/11.5 MB 16.7 MB/s eta 0:00:00
Downloading pytz-2025.2-py2.py3-none-any.whl (509 kB)
Downloading tzdata-2025.2-py2.py3-none-any.whl (347 kB)
Installing collected packages: pytz, tzdata, pandas
Successfully installed pandas-2.2.3 pytz-2025.2 tzdata-2025.2
Note: you may need to restart the kernel to use updated packages.

In [7]:
import pandas as pd
# creating a series: series stores the data irrespective of its data type:
data={'a':1,'b':'Tejaswi','c':3,'d':4}
series_dict=pd.Series(data)
print(series_dict)

a          1
b    Tejaswi
c          3
d          4
dtype: object

In [8]:
#DataFrame:creating a df from dictionary:
data={
    'Name':['Tejaswi','Dinesh','Vinayak'],
    'Age': [25,30,45],
    'City':['NewYork','Bangalore','Texas']
}

data1=pd.DataFrame(data)
print(data1)
print(type(data1))

      Name  Age       City
0  Tejaswi   25    NewYork
1   Dinesh   30  Bangalore
2  Vinayak   45      Texas
<class 'pandas.core.frame.DataFrame'>

In [10]:
#creating a df from list of dictinaries;

data=[
    {'Name':'Tejaswi','Age':55,'City':'Hyderbad'},
    {'Name':'Dinesh','Age':30,'City':'Chicago'},
    {'Name':'Vinayak','Age':21,'City':'Mumbai'},
    {'Name':'Siddartha','Age':22,'City':'Hyderbad'}
]

df = pd.DataFrame(data)
print(df)

        Name  Age      City
0    Tejaswi   55  Hyderbad
1     Dinesh   30   Chicago
2    Vinayak   21    Mumbai
3  Siddartha   22  Hyderbad

In [11]:
data2 =pd.read_csv('industry.csv')
#print(data)
data2.head()

                        Industry
0             Accounting/Finance
1   Advertising/Public Relations
2             Aerospace/Aviation
3  Arts/Entertainment/Publishing
4                     Automotive

In [12]:
data2.tail()

                    Industry
38             Skilled Labor
39                Technology
40        Telecommunications
41  Transportation/Logistics
42                     Other

In [13]:
df

        Name  Age      City
0    Tejaswi   55  Hyderbad
1     Dinesh   30   Chicago
2    Vinayak   21    Mumbai
3  Siddartha   22  Hyderbad

In [14]:
type(df['Name'])

pandas.core.series.Series

In [15]:
print(df.loc[0])  #Row indexing
df.iloc[1][0] #Column indexing

Name     Tejaswi
Age           55
City    Hyderbad
Name: 0, dtype: object

C:\Users\tejas\AppData\Local\Temp\ipykernel_20536\1556774910.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[1][0] #Column indexing

'Dinesh'

In [19]:
#Accessing the specified element:

print(df.at[1,'Age'])

30

In [23]:
df.drop(1,inplace=True)

In [24]:
df

        Name  Age      City
2    Vinayak   21    Mumbai
3  Siddartha   22  Hyderbad